# yaml-language-server: $schema=https://json.schemastore.org/spring-configuration-properties.json
spring:
  config:
    activate:
      on-profile: docker
  datasource:
    url: jdbc:postgresql://postgres:5432/${POSTGRES_DB}
    username: ${POSTGRES_USER:warehouse_user}
    password: ${POSTGRES_PASSWORD:change_me}
    driver-class-name: org.postgresql.Driver
  data:
    redis:
      host: ${REDIS_HOST:redis}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:admin123}
      lettuce:
        shutdown-timeout: 100ms

management:
  endpoint:
    health:
      show-details: always

server:
  port: ${SERVER_PORT:8080}