global:
  resolve_timeout: 5m

route:
  group_by: ['alertname', 'severity']
  group_wait: 10s
  group_interval: 15s
  repeat_interval: 5m
  receiver: 'webhook-default'

receivers:
  - name: 'webhook-default'
    webhook_configs:
      - url: 'http://webhook-server:8082/webhook'
        send_resolved: true
        max_alerts: 10