apiVersion: 1

datasources:
  - name: Tempo
    uid: tempo
    type: tempo
    access: proxy
    url: http://tempo:3200
    jsonData:
      tracesToLogsV2:
        datasourceUid: loki
        tags:
          - key: 'service.name'
            value: 'application'
          - key: 'level'
            value: 'level'
        spanStartTimeShift: '-5m'
        spanEndTimeShift: '5m'
        filterByTraceID: true