name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:dind
        privileged: true
        options: >-
          --name=docker-daemon
          --storage-driver=overlay2
        ports:
          - 2375:2375
        environment:
          DOCKER_TLS_CERTDIR: ""

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build and test
        run: |
          chmod +x gradlew
          DOCKER_HOST=tcp://localhost:2375 ./gradlew clean build --no-daemon
